name: ddev-phpunittesting
networks:
    ddev_default:
        external: true
        name: ddev_default
    default:
        name: ddev-phpunittesting_default
services:
    db:
        build:
            args:
                BASE_IMAGE: ddev/ddev-dbserver-mariadb-10.4:v1.22.0
                gid: "1000"
                uid: "1000"
                username: weiner
            context: /home/weiner/Sites/phpunittesting/.ddev/.dbimageBuild
            dockerfile: Dockerfile
        cap_add:
            - SYS_NICE
        command: []
        container_name: ddev-phpunittesting-db
        environment:
            COLUMNS: "62"
            DDEV_DATABASE: mariadb:10.4
            DDEV_DATABASE_FAMILY: mysql
            DDEV_HOSTNAME: phpunittesting.ddev.site
            DDEV_PHP_VERSION: "8.1"
            DDEV_PRIMARY_URL: https://phpunittesting.ddev.site
            DDEV_PROJECT: phpunittesting
            DDEV_PROJECT_TYPE: drupal10
            DDEV_ROUTER_HTTP_PORT: "80"
            DDEV_ROUTER_HTTPS_PORT: "443"
            DDEV_SITENAME: phpunittesting
            DDEV_TLD: ddev.site
            DOCKER_IP: 127.0.0.1
            GOARCH: amd64
            GOOS: linux
            HOST_DOCKER_INTERNAL_IP: ""
            IS_DDEV_PROJECT: "true"
            LINES: "32"
            MYSQL_HISTFILE: /mnt/ddev-global-cache/mysqlhistory/phpunittesting-db/mysql_history
            MYSQL_PWD: db
            PGDATABASE: db
            PGHOST: 127.0.0.1
            PGPASSWORD: db
            PGUSER: db
            POSTGRES_DB: db
            POSTGRES_PASSWORD: db
            POSTGRES_USER: db
            TZ: ""
            USER: weiner
        healthcheck:
            interval: 1s
            retries: 120
            start_period: 2m0s
            timeout: 2m0s
        hostname: phpunittesting-db
        image: ddev/ddev-dbserver-mariadb-10.4:v1.22.0-phpunittesting-built
        labels:
            com.ddev.app-type: drupal10
            com.ddev.approot: /home/weiner/Sites/phpunittesting
            com.ddev.platform: ddev
            com.ddev.site-name: phpunittesting
        networks:
            ddev_default: null
            default: null
        ports:
            - host_ip: 127.0.0.1
              mode: ingress
              protocol: tcp
              published: "32795"
              target: 3306
        restart: "no"
        stop_grace_period: 1m0s
        user: 1000:1000
        volumes:
            - source: database
              target: /var/lib/mysql
              type: volume
              volume:
                nocopy: true
            - bind:
                create_host_path: true
              source: /home/weiner/Sites/phpunittesting/.ddev
              target: /mnt/ddev_config
              type: bind
            - bind:
                create_host_path: true
              source: /home/weiner/Sites/phpunittesting/.ddev/db_snapshots
              target: /mnt/snapshots
              type: bind
            - source: ddev-global-cache
              target: /mnt/ddev-global-cache
              type: volume
              volume: {}
        working_dir: /home/weiner
    web:
        build:
            args:
                BASE_IMAGE: ddev/ddev-webserver:v1.22.0
                DDEV_PHP_VERSION: "8.1"
                gid: "1000"
                uid: "1000"
                username: weiner
            context: /home/weiner/Sites/phpunittesting/.ddev/.webimageBuild
            dockerfile: Dockerfile
        cap_add:
            - SYS_PTRACE
        command:
            - /pre-start.sh
        container_name: ddev-phpunittesting-web
        environment:
            BLACKFIRE_CLIENT_ID: 59e852ef-6fde-4624-b951-0a6c6b298747
            BLACKFIRE_CLIENT_TOKEN: 20efa025ddb32b8d565ef6df8bc855dcef22db7885b5eed861647aac7a8fb066
            BLACKFIRE_SERVER_ID: 834190d3-9802-4b30-aa2a-d7f1370b43af
            BLACKFIRE_SERVER_TOKEN: a6b3a6a70c13ffbc3ecaa180e943123810e59ec05d6132cec8b85270278dea7b
            COLUMNS: "62"
            DDEV_COMPOSER_ROOT: /var/www/html
            DDEV_DATABASE: mariadb:10.4
            DDEV_DATABASE_FAMILY: mysql
            DDEV_DOCROOT: web
            DDEV_FILES_DIR: /var/www/html/web/sites/default/files
            DDEV_FILES_DIRS: /var/www/html/web/sites/default/files
            DDEV_HOSTNAME: phpunittesting.ddev.site
            DDEV_MUTAGEN_ENABLED: "false"
            DDEV_PHP_VERSION: "8.1"
            DDEV_PRIMARY_URL: https://phpunittesting.ddev.site
            DDEV_PROJECT: phpunittesting
            DDEV_PROJECT_TYPE: drupal10
            DDEV_ROUTER_HTTP_PORT: "80"
            DDEV_ROUTER_HTTPS_PORT: "443"
            DDEV_SITENAME: phpunittesting
            DDEV_TLD: ddev.site
            DDEV_VERSION: v1.22.0
            DDEV_WEB_ENTRYPOINT: /mnt/ddev_config/web-entrypoint.d
            DDEV_WEBSERVER_TYPE: nginx-fpm
            DDEV_XDEBUG_ENABLED: "false"
            DEPLOY_NAME: local
            DOCKER_IP: 127.0.0.1
            DOCROOT: web
            DRUSH_ALLOW_XDEBUG: "1"
            DRUSH_OPTIONS_URI: https://phpunittesting.ddev.site
            GOARCH: amd64
            GOOS: linux
            HOST_DOCKER_INTERNAL_IP: ""
            HTTP_EXPOSE: 80:80,8025:8025
            HTTPS_EXPOSE: 443:80,8026:8025
            IS_DDEV_PROJECT: "true"
            LINES: "32"
            MYSQL_HISTFILE: /mnt/ddev-global-cache/mysqlhistory/phpunittesting-web/mysql_history
            MYSQL_PWD: db
            NODE_EXTRA_CA_CERTS: /mnt/ddev-global-cache/mkcert/rootCA.pem
            PGDATABASE: db
            PGHOST: db
            PGPASSWORD: db
            PGUSER: db
            PHP_IDE_CONFIG: serverName=phpunittesting.ddev.site
            SSH_AUTH_SOCK: /home/.ssh-agent/socket
            TZ: ""
            USER: weiner
            VIRTUAL_HOST: phpunittesting.ddev.site
            npm_config_cache: /mnt/ddev-global-cache/npm
        external_links:
            - ddev-router:phpunittesting.ddev.site
        extra_hosts:
            - host.docker.internal:host-gateway
        healthcheck:
            interval: 1s
            retries: 120
            start_period: 2m0s
            timeout: 2m0s
        hostname: phpunittesting-web
        image: ddev/ddev-webserver:v1.22.0-phpunittesting-built
        labels:
            com.ddev.app-type: drupal10
            com.ddev.approot: /home/weiner/Sites/phpunittesting
            com.ddev.platform: ddev
            com.ddev.site-name: phpunittesting
        networks:
            ddev_default: null
            default: null
        ports:
            - host_ip: 127.0.0.1
              mode: ingress
              protocol: tcp
              target: 80
            - host_ip: 127.0.0.1
              mode: ingress
              protocol: tcp
              target: 443
        restart: "no"
        user: 1000:1000
        volumes:
            - consistency: cached
              source: ../
              target: /var/www/html
              type: bind
            - bind:
                create_host_path: true
              read_only: true
              source: /home/weiner/Sites/phpunittesting/.ddev
              target: /mnt/ddev_config
              type: bind
            - bind:
                create_host_path: true
              read_only: true
              source: /home/weiner/Sites/phpunittesting/.ddev/xhprof
              target: /usr/local/bin/xhprof
              type: bind
            - source: ddev-global-cache
              target: /mnt/ddev-global-cache
              type: volume
              volume: {}
            - source: ddev-ssh-agent_socket_dir
              target: /home/.ssh-agent
              type: volume
              volume: {}
        working_dir: /var/www/html/
volumes:
    database:
        external: true
        name: phpunittesting-mariadb
    ddev-global-cache:
        external: true
        name: ddev-global-cache
    ddev-ssh-agent_socket_dir:
        external: true
        name: ddev-ssh-agent_socket_dir
